import type { DefenseItem } from "@/shared/types/defense-configuration";

function mapOnlyItem({
  id,
  title,
  groupId,
  layerId,
  echelonId,
  assetTemplateId,
  score,
  pricePerUnitMln,
}: {
  id: string;
  title: string;
  groupId: string;
  layerId: DefenseItem["layerId"];
  echelonId: string;
  assetTemplateId: string;
  score: number;
  pricePerUnitMln: number;
}): DefenseItem {
  return {
    id,
    title,
    shortTitle: title,
    mapCatalogGroupIds: [groupId],
    mapAssetTemplateId: assetTemplateId,
    calculatorAssetId: null,
    layerId,
    echelonId,
    unitLabel: "шт",
    pricePerUnitMln,
    currency: "RUB",
    maxQuantity: 1,
    score,
    priority: score >= 20 ? "primary" : "medium",
    coverageWeight: score,
  };
}

const mapOnlyDefenseItems: DefenseItem[] = [
  mapOnlyItem({ id: "l1-emergency-centers", title: "Региональные центры МЧС", groupId: "l1-emergency-centers", layerId: "layer_01_external_warning", echelonId: "ech_1_external_warning", assetTemplateId: "asset-radar-l2", score: 18, pricePerUnitMln: 8 }),
  mapOnlyItem({ id: "l1-military-command", title: "Военная комендатура", groupId: "l1-military-command", layerId: "layer_01_external_warning", echelonId: "ech_1_external_warning", assetTemplateId: "asset-radar-l2", score: 16, pricePerUnitMln: 12 }),
  mapOnlyItem({ id: "l1-regional-hq", title: "Оперативный штаб региона / ФСБ-куратор", groupId: "l1-regional-hq", layerId: "layer_01_external_warning", echelonId: "ech_1_external_warning", assetTemplateId: "asset-radar-l2", score: 22, pricePerUnitMln: 15 }),
  mapOnlyItem({ id: "l1-neighbor-network", title: "Сетка соседних предприятий", groupId: "l1-neighbor-network", layerId: "layer_01_external_warning", echelonId: "ech_1_external_warning", assetTemplateId: "asset-radar-l2", score: 14, pricePerUnitMln: 6 }),
  mapOnlyItem({ id: "l1-osint", title: "OSINT-мониторинг", groupId: "l1-osint", layerId: "layer_01_external_warning", echelonId: "ech_1_external_warning", assetTemplateId: "asset-radar-l2", score: 12, pricePerUnitMln: 4 }),
  mapOnlyItem({ id: "l2-optical", title: "Оптико-электронные системы", groupId: "l2-optical", layerId: "layer_02_detection", echelonId: "ech_2_detection", assetTemplateId: "asset-radar-l2", score: 18, pricePerUnitMln: 12 }),
  mapOnlyItem({ id: "l2-thermal", title: "Тепловизионные системы", groupId: "l2-thermal", layerId: "layer_02_detection", echelonId: "ech_2_detection", assetTemplateId: "asset-radar-l2", score: 16, pricePerUnitMln: 10 }),
  mapOnlyItem({ id: "l2-acoustic", title: "Акустические массивы", groupId: "l2-acoustic", layerId: "layer_02_detection", echelonId: "ech_2_detection", assetTemplateId: "asset-radar-l2", score: 14, pricePerUnitMln: 6 }),
  mapOnlyItem({ id: "l2-rf-passive", title: "Пассивные радиочастотные детекторы", groupId: "l2-rf-passive", layerId: "layer_02_detection", echelonId: "ech_2_detection", assetTemplateId: "asset-radar-l2", score: 16, pricePerUnitMln: 9 }),
  mapOnlyItem({ id: "l3-classification", title: "ПО классификации целей", groupId: "l3-classification", layerId: "layer_03_identification", echelonId: "ech_2_detection", assetTemplateId: "asset-radar-l2", score: 20, pricePerUnitMln: 5 }),
  mapOnlyItem({ id: "l4-gps-spoof", title: "GPS-спуферы", groupId: "l4-gps-spoof", layerId: "layer_04_suppression", echelonId: "ech_3_suppression", assetTemplateId: "asset-ew-l4", score: 16, pricePerUnitMln: 9 }),
  mapOnlyItem({ id: "l4-microwave", title: "СВЧ-оружие", groupId: "l4-microwave", layerId: "layer_04_suppression", echelonId: "ech_3_suppression", assetTemplateId: "asset-ew-l4", score: 18, pricePerUnitMln: 120 }),
  mapOnlyItem({ id: "l5-mobile-fire", title: "МОГ", groupId: "l5-mobile-fire", layerId: "layer_05_mid_range_kinetic", echelonId: "ech_4_fire_priority", assetTemplateId: "asset-kinetic-l6", score: 15, pricePerUnitMln: 35 }),
  mapOnlyItem({ id: "l5-bars", title: "БАРС", groupId: "l5-bars", layerId: "layer_05_mid_range_kinetic", echelonId: "ech_4_fire_priority", assetTemplateId: "asset-kinetic-l6", score: 16, pricePerUnitMln: 28 }),
  mapOnlyItem({ id: "l6-pzrk", title: "ПЗРК", groupId: "l6-pzrk", layerId: "layer_06_last_line_kinetic", echelonId: "ech_5_fire_reserve", assetTemplateId: "asset-kinetic-l6", score: 18, pricePerUnitMln: 18 }),
  mapOnlyItem({ id: "l7-camouflage", title: "Маскировочные сети и экраны", groupId: "l7-camouflage", layerId: "layer_07_accuracy_disruption", echelonId: "ech_6_passive_itz", assetTemplateId: "asset-ew-l4", score: 16, pricePerUnitMln: 14 }),
  mapOnlyItem({ id: "l7-smoke", title: "Дымогенерация", groupId: "l7-smoke", layerId: "layer_07_accuracy_disruption", echelonId: "ech_6_passive_itz", assetTemplateId: "asset-ew-l4", score: 12, pricePerUnitMln: 8 }),
  mapOnlyItem({ id: "l7-thermal-decoy", title: "Ложные тепловые сигнатуры", groupId: "l7-thermal-decoy", layerId: "layer_07_accuracy_disruption", echelonId: "ech_6_passive_itz", assetTemplateId: "asset-ew-l4", score: 14, pricePerUnitMln: 6 }),
  mapOnlyItem({ id: "l7-decoys", title: "Макеты-обманки", groupId: "l7-decoys", layerId: "layer_07_accuracy_disruption", echelonId: "ech_6_passive_itz", assetTemplateId: "asset-ew-l4", score: 12, pricePerUnitMln: 5 }),
  mapOnlyItem({ id: "l7-contrast", title: "Снижение оптического и ИК-контраста", groupId: "l7-contrast", layerId: "layer_07_accuracy_disruption", echelonId: "ech_6_passive_itz", assetTemplateId: "asset-ew-l4", score: 14, pricePerUnitMln: 10 }),
  mapOnlyItem({ id: "l8-domes", title: "Купола и аэростаты", groupId: "l8-domes", layerId: "layer_08_passive_protection", echelonId: "ech_6_passive_itz", assetTemplateId: "asset-passive-l8", score: 16, pricePerUnitMln: 45 }),
];

export const defenseItems: DefenseItem[] = [
  ...mapOnlyDefenseItems,
  {
    id: "mobile-radar",
    title: "Мобильный РЛС",
    shortTitle: "РЛС",
    mapCatalogGroupIds: ["l2-radar"],
    mapAssetTemplateId: "asset-radar-l2",
    calculatorAssetId: "mobile-radar",
    layerId: "layer_02_detection",
    echelonId: "ech_2_detection",
    rangeLabel: "5-75 км",
    unitLabel: "шт",
    pricePerUnitMln: 20,
    currency: "RUB",
    maxQuantity: 6,
    score: 79,
    priority: "primary",
    coverageWeight: 79,
  },
  {
    id: "ew-narrowband",
    title: "РЭБ узкополосный (против GNSS)",
    mapCatalogGroupIds: ["l4-ew-gnss"],
    mapAssetTemplateId: "asset-ew-l4",
    calculatorAssetId: "ew-narrowband",
    layerId: "layer_04_suppression",
    echelonId: "ech_3_suppression",
    rangeLabel: "2-10 км",
    unitLabel: "шт",
    pricePerUnitMln: 15,
    currency: "RUB",
    maxQuantity: 6,
    score: 78,
    priority: "primary",
    coverageWeight: 78,
  },
  {
    id: "ew-broadband",
    title: "РЭБ широкополосный (против радиоканалов)",
    mapCatalogGroupIds: ["l4-ew-radio"],
    mapAssetTemplateId: "asset-ew-l4",
    calculatorAssetId: "ew-broadband",
    layerId: "layer_04_suppression",
    echelonId: "ech_3_suppression",
    rangeLabel: "2-10 км",
    unitLabel: "шт",
    pricePerUnitMln: 18,
    currency: "RUB",
    maxQuantity: 6,
    score: 74,
    priority: "primary",
    coverageWeight: 74,
  },
  {
    id: "interceptor-drones",
    title: "Дроны-перехватчики",
    mapCatalogGroupIds: ["l5-interceptor"],
    mapAssetTemplateId: "asset-kinetic-l6",
    calculatorAssetId: "interceptor-drones",
    layerId: "layer_05_mid_range_kinetic",
    echelonId: "ech_4_fire_priority",
    rangeLabel: "1-20 км",
    unitLabel: "комплект",
    pricePerUnitMln: 7,
    currency: "RUB",
    maxQuantity: 6,
    score: 74,
    priority: "primary",
    coverageWeight: 74,
  },
  {
    id: "aircraft",
    title: "Самолёты",
    mapCatalogGroupIds: [],
    calculatorAssetId: "aircraft",
    layerId: "layer_05_mid_range_kinetic",
    echelonId: "ech_4_fire_priority",
    rangeLabel: "1-20 км",
    unitLabel: "шт",
    pricePerUnitMln: 20,
    currency: "RUB",
    maxQuantity: 3,
    score: 72,
    priority: "primary",
    coverageWeight: 72,
  },
  {
    id: "turret-complex",
    title: "Турельный комплекс",
    mapCatalogGroupIds: ["l5-turret"],
    mapAssetTemplateId: "asset-kinetic-l6",
    calculatorAssetId: "turret-complex",
    layerId: "layer_05_mid_range_kinetic",
    echelonId: "ech_4_fire_priority",
    rangeLabel: "1-20 км",
    unitLabel: "шт",
    pricePerUnitMln: 7.9,
    currency: "RUB",
    maxQuantity: 6,
    score: 80,
    priority: "primary",
    coverageWeight: 80,
  },
  {
    id: "armored-vehicle",
    title: "Бронеавтомобиль",
    mapCatalogGroupIds: [],
    calculatorAssetId: "armored-vehicle",
    layerId: "layer_05_mid_range_kinetic",
    echelonId: "ech_4_fire_priority",
    rangeLabel: "1-20 км",
    unitLabel: "шт",
    pricePerUnitMln: 28,
    currency: "RUB",
    maxQuantity: 6,
    score: 70,
    priority: "primary",
    coverageWeight: 70,
  },
  {
    id: "laser",
    title: "Лазер",
    mapCatalogGroupIds: ["l4-laser"],
    mapAssetTemplateId: "asset-ew-l4",
    calculatorAssetId: "laser",
    layerId: "layer_06_last_line_kinetic",
    echelonId: "ech_5_fire_reserve",
    rangeLabel: "до 1,5 км",
    unitLabel: "шт",
    pricePerUnitMln: 690,
    currency: "RUB",
    maxQuantity: 1,
    score: 40,
    priority: "low",
    coverageWeight: 40,
  },
  {
    id: "barrel-aa",
    title: "Ствольная ПВО",
    mapCatalogGroupIds: ["l6-barrel"],
    mapAssetTemplateId: "asset-kinetic-l6",
    calculatorAssetId: "barrel-aa",
    layerId: "layer_06_last_line_kinetic",
    echelonId: "ech_5_fire_reserve",
    rangeLabel: "до 1,5 км",
    unitLabel: "шт",
    pricePerUnitMln: 290,
    currency: "RUB",
    maxQuantity: 2,
    score: 60,
    priority: "medium",
    coverageWeight: 60,
  },
  {
    id: "pantsir-zrpk",
    title: "ЗРПК «Панцирь»",
    mapCatalogGroupIds: ["l6-zrpk"],
    mapAssetTemplateId: "asset-kinetic-l6",
    calculatorAssetId: "pantsir-zrpk",
    layerId: "layer_06_last_line_kinetic",
    echelonId: "ech_5_fire_reserve",
    rangeLabel: "до 1,5 км",
    unitLabel: "шт",
    pricePerUnitMln: 850,
    currency: "RUB",
    maxQuantity: 2,
    score: 58,
    priority: "medium",
    coverageWeight: 58,
  },
  {
    id: "passive-itz-bundle",
    title: "Тросы, сетки, укрепление критических узлов и т.п.",
    mapCatalogGroupIds: ["l8-anti-drone-nets", "l8-cable-systems", "l9-armoring", "l9-spacing"],
    mapAssetTemplateId: "asset-passive-l8",
    calculatorAssetId: "passive-itz-bundle",
    layerId: "layer_08_passive_protection",
    echelonId: "ech_6_passive_itz",
    rangeLabel: "0,5-2 км, на узлах",
    unitLabel: "комплект",
    pricePerUnitMln: 174,
    currency: "RUB",
    maxQuantity: 1,
    score: 55,
    priority: "medium",
    coverageWeight: 55,
  },
  {
    id: "atz-bundle",
    title: "КПП и защита персонала (бомбоубежища и т.п.)",
    mapCatalogGroupIds: [],
    calculatorAssetId: "atz-bundle",
    layerId: "layer_09_hardening",
    echelonId: "ech_7_atz",
    rangeLabel: "n/a",
    unitLabel: "комплект",
    pricePerUnitMln: 122,
    currency: "RUB",
    maxQuantity: 1,
    score: 52,
    priority: "medium",
    coverageWeight: 52,
  },
  {
    id: "command-post",
    title: "Командный пункт",
    mapCatalogGroupIds: [],
    calculatorAssetId: "command-post",
    layerId: "layer_01_external_warning",
    echelonId: "ech_8_infrastructure",
    rangeLabel: "на всех эшелонах",
    unitLabel: "шт",
    pricePerUnitMln: 25,
    currency: "RUB",
    maxQuantity: 1,
    score: 79,
    priority: "primary",
    coverageWeight: 79,
  },
];

export function getDefenseItemById(itemId: string): DefenseItem | undefined {
  return defenseItems.find((item) => item.id === itemId);
}

export function getDefenseItemByMapGroupId(groupId: string): DefenseItem | undefined {
  return defenseItems.find((item) => item.mapCatalogGroupIds.includes(groupId));
}

export function getDefenseItemByCalculatorAssetId(assetId: string): DefenseItem | undefined {
  return defenseItems.find((item) => item.calculatorAssetId === assetId);
}

export const defensePresetConfigurations = [
  {
    id: "nak",
    name: "НАК",
    selectedItems: {
      "mobile-radar": 6,
      "interceptor-drones": 6,
      aircraft: 2,
      "turret-complex": 6,
      "armored-vehicle": 6,
      "barrel-aa": 2,
      "passive-itz-bundle": 1,
      "atz-bundle": 1,
      "command-post": 1,
    },
  },
  {
    id: "nev",
    name: "НЕВ",
    selectedItems: {
      "mobile-radar": 1,
      "interceptor-drones": 1,
      aircraft: 2,
      "turret-complex": 1,
      "armored-vehicle": 1,
      laser: 1,
      "passive-itz-bundle": 1,
      "atz-bundle": 1,
      "command-post": 1,
    },
  },
  {
    id: "fosforit",
    name: "ФОСФОРИТ",
    selectedItems: {
      "mobile-radar": 4,
      "interceptor-drones": 4,
      aircraft: 3,
      "turret-complex": 4,
      "armored-vehicle": 4,
      laser: 1,
      "barrel-aa": 2,
      "passive-itz-bundle": 1,
      "atz-bundle": 1,
      "command-post": 1,
    },
  },
  {
    id: "bmu",
    name: "БМУ",
    selectedItems: {
      "mobile-radar": 3,
      "interceptor-drones": 3,
      aircraft: 2,
      "turret-complex": 3,
      "armored-vehicle": 3,
      laser: 1,
      "passive-itz-bundle": 1,
      "atz-bundle": 1,
      "command-post": 1,
    },
  },
] as const;
